#!/bin/bash
# @author: Dr.-Ing. XAVIER NOUNDOU

ALL_YERITH_CODEBASE_CPP_FILES="${YERITH_ERP_3_0_HOME_FOLDER}/yerith-ALL-USER-ENABLING-ACTIONS-WINDOWS.TXT"

function generate_init_user_action_rights_txt 
{
	CURRENT_YERITH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX="${1}"

	YERITH_TEXT_TO_REPLACE_OR_FILE="${CURRENT_YERITH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS.txt"
	
	yerith-GENERATE-FOR-FILE-CPP-USER-ENABLING-ACTION-CPP-COMMANDS.sh \
		-i "${YERITH_TEXT_TO_REPLACE_OR_FILE}" \
		-o "${CURRENT_YERITH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS-cpp-COMMANDS.txt"
	
	YERITH_TEXT_TO_PLACE_INSIDE_CODE="$(cat "${CURRENT_YERITH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS-cpp-COMMANDS.txt")"

	sed -i \
		"s|CONSTRUCTOR_USER_ACTION_RIGHTS|${YERITH_TEXT_TO_PLACE_INSIDE_CODE}|g" \
		"${CURRENT_YERITH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}.cpp"

	rm "${CURRENT_YERITH_ERP_3_0_CPP_SOURCE_FILE_BASE_NAME_PREFIX}-INIT-USER-ACTION-RIGHTS-cpp-COMMANDS.txt"
}

while read LINE; do
	LINE="${YERITH_ERP_3_0_HOME_FOLDER}/${LINE}"
	generate_init_user_action_rights_txt "${LINE%%".cpp"}"
done < "$ALL_YERITH_CODEBASE_CPP_FILES"

