/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c IYRIruntimeverificationAdaptor_Interface -p src/IYRIruntimeverificationAdaptor_interface.h:src/IYRIruntimeverificationAdaptor_interface.cpp src/dbus/yri.db-runtime.verif.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "src/IYRIruntimeverificationAdaptor_interface.h"

/*
 * Implementation of interface class IYRIruntimeverificationAdaptor_Interface
 */

IYRIruntimeverificationAdaptor_Interface::IYRIruntimeverificationAdaptor_Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

IYRIruntimeverificationAdaptor_Interface::~IYRIruntimeverificationAdaptor_Interface()
{
}

